name: Aggiorna file teorica

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [sample_push]
  workflow_dispatch:

jobs:
  copy_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: danielediprima/teorica
        ref: main
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}


    - name: list
      run: pwd && ls && cp ./teorica_definitivo/teorica_def_1.pdf ../

    - name: Checkout public repository
      uses: actions/checkout@v2
      #with:
      #  #repository: danielediprima/lezioni_relativita_ristretta
      #  ref: main

    - name: Copy file from private to public repository
      run: pwd && ls && mv ../teorica_def_1.pdf ./
      
    - name: Update Repository
      run: |-
        git config user.name "autoupdate"
        git config user.email "actions@users.noreply.github.com"
        git add *
        timestamp=$(date --iso-8601=seconds)
        git commit -am "update: ${timestamp}" || exit 0
        git push
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
